# Generated by Django 5.0.4 on 2024-04-07 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='clouds_p',
        ),
        migrations.RemoveField(
            model_name='route',
            name='description',
        ),
        migrations.RemoveField(
            model_name='route',
            name='description_p',
        ),
        migrations.RemoveField(
            model_name='route',
            name='name_p',
        ),
        migrations.RemoveField(
            model_name='route',
            name='precipitation',
        ),
        migrations.RemoveField(
            model_name='route',
            name='precipitation_sum_l',
        ),
        migrations.RemoveField(
            model_name='route',
            name='precipitation_sum_p',
        ),
        migrations.RemoveField(
            model_name='route',
            name='sunrise',
        ),
        migrations.RemoveField(
            model_name='route',
            name='sunset',
        ),
        migrations.RemoveField(
            model_name='route',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='route',
            name='temperature_2m_max',
        ),
        migrations.RemoveField(
            model_name='route',
            name='temperature_2m_min',
        ),
        migrations.RemoveField(
            model_name='route',
            name='wind',
        ),
        migrations.RemoveField(
            model_name='route',
            name='wind_gust',
        ),
        migrations.AlterField(
            model_name='route',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='forecast.category', verbose_name='Категория'),
        ),
    ]
