# Generated by Django 5.0.4 on 2024-04-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_remove_route_clouds_p_remove_route_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='distance_km',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Дистанция'),
        ),
    ]
